# Generated by Django 5.2.7 on 2025-11-07 20:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_istat_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('reg_name', models.CharField(max_length=200)),
                ('reg_acronym', models.CharField(max_length=2)),
                ('reg_poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('reg_centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('prov_istat_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('prov_name', models.CharField(max_length=200)),
                ('prov_acronym', models.CharField(max_length=2)),
                ('prov_poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('prov_centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='igp_doc_food_tracker.region')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('igp', 'I.G.P.'), ('dop', 'D.O.P.'), ('stg', 'S.T.G.')], max_length=3)),
                ('food_type', models.CharField(max_length=100)),
                ('recipe', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_fp', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('eaten', models.BooleanField(default=False)),
                ('loc_eaten', models.CharField(blank=True, max_length=1000, null=True)),
                ('point_eaten', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('provinces', models.ManyToManyField(related_name='foods', to='igp_doc_food_tracker.province')),
                ('regions', models.ManyToManyField(related_name='foods', to='igp_doc_food_tracker.region')),
            ],
        ),
    ]
