# Generated by Django 5.2.7 on 2025-11-10 18:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='prov_poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
