# Generated by Django 5.2.7 on 2025-11-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0002_alter_province_prov_poly_alter_region_reg_poly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='parent_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='igp_doc_food_tracker.region'),
        ),
    ]
