# Generated by Django 5.2.7 on 2025-11-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0003_alter_province_parent_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='provinces',
        ),
        migrations.RemoveField(
            model_name='food',
            name='regions',
        ),
    ]
