# Generated by Django 5.2.7 on 2025-11-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0004_remove_food_provinces_remove_food_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=3),
        ),
    ]
