# Generated by Django 5.2.7 on 2025-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0005_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='provinces',
            field=models.ManyToManyField(related_name='foods', to='igp_doc_food_tracker.province'),
        ),
        migrations.AddField(
            model_name='food',
            name='regions',
            field=models.ManyToManyField(related_name='foods', to='igp_doc_food_tracker.region'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('igp', 'I.G.P.'), ('dop', 'D.O.P.'), ('stg', 'S.T.G.')], max_length=3),
        ),
    ]
