# Generated by Django 5.2.7 on 2025-11-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0006_food_provinces_food_regions_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(max_length=500),
        ),
    ]
