# Generated by Django 5.2.7 on 2025-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0007_alter_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type_eng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
