# Generated by Django 5.2.7 on 2025-12-15 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igp_doc_food_tracker', '0008_food_food_type_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, editable=False, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='region',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, editable=False, null=True, srid=4326),
        ),
    ]
